default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["self_improvement_db_user"] %>
  password: <%= ENV["UwqAzoSaO7dXHcMN59y4dXcXVb6qzZtr"] %>
  host: <%= ENV["dpg-d0h2d9idbo4c73bthj10-a"] %>

development:
  <<: *default
  database: self_improvement_ai_development

test:
  <<: *default
  database: self_improvement_ai_test

production:
  <<: *default
  database: self_improvement_ai_production